[Unit]
ConditionPathExists=!/var/run/qubes/this-is-templatevm
ConditionPathExists=/var/run/qubes-service/vpn-exclude-domains

After=qubes-firewall.service rw.mount qubes-vpn-handler.service
BindsTo=qubes-vpn-handler.service

[Service]
ExecStartPre=/rw/config/qubes-vpn-exclude/generate-dnsmasq.sh
ExecStopPost=-/usr/sbin/ipset flush qubes-vpn-exclude-4
ExecStopPost=-/usr/sbin/ipset flush qubes-vpn-exclude-6

[Install]
WantedBy=qubes-vpn-handler.service
